### ISSUE TITLE
Why a class BaselineOutput ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/baselines#17]
There is no method associated with this class so I think we should directly return an object.

Classes can yield to some problems (when using immer for example) and for those 'core' calculation packages it is better to avoid them.

**Comment by kjappelbaum** [comment]
i wanted to be more consistent and make jsdoc easier but i can revert this.

**Comment by lpatiny** [comment]
For jsdoc it make sense indeed. But in order to keep this feature in jsdoc you can use typedef like in 
https://github.com/mljs/spectra-processing/blob/master/src/index.js#L1-L16
