### ISSUE TITLE
Optional xs in options

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/baselines#20]
In the following lines:

https://github.com/cheminfo/baselines/blob/4e5da3f5762dc5c0fb8869abfe3c5332610ac356/src/iterativePolynomial.js#L25-L30

I would move the 'x' argument to options ... if it is optional. I would call it 'xs'.

Also for a 'sequential fill' you may use: https://github.com/mljs/array/blob/master/packages/array-sequential-fill/README.md

It should be faster.

**Comment by kjappelbaum** [comment]
wasn't sure about this one as this is somewhat more than a simple option (the assumption of linear spacing is not always a good one)
